name: dart_mc_ping
description: A Dart implementation of the Minecraft ping protocol (https://wiki.vg/Server_List_Ping)
version: 1.0.ยง
homepage: https://github.com/Nomeyho/dart_mc_ping

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  raw: ^0.2.0
  logging: ^0.11.4
  fixnum: ^0.10.11
  colorize: ^2.0.0

dev_dependencies:
  test: ^1.9.4
